# Generated by Django 4.2.6 on 2023-10-20 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="test",
            new_name="text",
        ),
    ]
